"use client";

import { useState } from "react";
import { AlertTriangle, ArrowLeft, ArrowUpRight, Bell, Boxes, CalendarDays, ChevronRight, CircleGauge, ClipboardCheck, Clock3, Filter, Gauge, LayoutDashboard, MapPin, PackageCheck, Search, Settings2, ShieldAlert, Truck, Wrench } from "lucide-react";

type View = "overview" | "equipment" | "inventory" | "maintenance";
type PartLine = { part: string; number: string; stock: string; minimum: string; cost: string; status: "Ready" | "Reorder" | "No stock" };
type MaintenanceLine = { id: string; type: string; date: string; description: string; condition: string; cost: string };
type EquipmentProfile = {
  id: string; name: string; model: string; status: string; condition: string; risk: number; hours: string; issue: string;
  inventory: PartLine[]; maintenance: MaintenanceLine[]; totalMaintenanceCost: string; operatingCost: string; predictedFailure: string;
};

const nav = [["overview","Operations overview",LayoutDashboard],["equipment","Equipment status",Truck],["inventory","Inventory status",Boxes],["maintenance","Maintenance history",Wrench]] as const;

const equipment: EquipmentProfile[] = [
  { id:"NR-05", name:"Haul Truck 05", model:"CAT 797F", status:"Operational", condition:"Poor", risk:82, hours:"12,400", issue:"Oil pressure warning", totalMaintenanceCost:"$38,450", operatingCost:"$14.20 / hour", predictedFailure:"Engine bearing failure",
    inventory:[{part:"Engine oil filter",number:"FLT-ENG-797",stock:"1 available",minimum:"5",cost:"$2,775",status:"Reorder"},{part:"Engine oil 15W-40",number:"LUB-15W40-205",stock:"45 L",minimum:"100 L",cost:"$1,900",status:"Reorder"},{part:"Engine bearing set",number:"BRG-ENG-797",stock:"0 available",minimum:"1",cost:"$3,200",status:"No stock"},{part:"Engine gasket set",number:"KIT-GSK-797",stock:"1 set",minimum:"2",cost:"$2,900",status:"Reorder"}],
    maintenance:[{id:"MNT-093",type:"Diagnostic",date:"Aug 29, 2026",description:"Recurring oil-pressure warning; bearing noise suspected",condition:"Poor",cost:"$4,800"},{id:"MNT-081",type:"Corrective",date:"Aug 14, 2026",description:"Inspected recurring lubrication issue",condition:"Poor",cost:"$7,250"},{id:"MNT-067",type:"Preventive",date:"Jul 26, 2026",description:"Engine service; abnormal vibration found",condition:"Poor",cost:"$9,100"},{id:"MNT-052",type:"Corrective",date:"Jul 02, 2026",description:"Repaired engine oil leak; warning returned",condition:"Poor",cost:"$11,600"},{id:"MNT-041",type:"Corrective",date:"Jun 11, 2026",description:"Investigated low oil-pressure alarm",condition:"Fair",cost:"$5,700"}], totalMaintenanceCost:"$38,450", operatingCost:"$14.20 / hour", predictedFailure:"Engine bearing failure" },
  { id:"NR-12", name:"Haul Truck 12", model:"CAT 793F", status:"Operational", condition:"Fair", risk:58, hours:"8,200", issue:"Hydraulic temperature", predictedFailure:"Hydraulic pump wear", totalMaintenanceCost:"$21,680", operatingCost:"$11.85 / hour",
    inventory:[{part:"Hydraulic return filter",number:"FLT-HYD-793",stock:"8 available",minimum:"4",cost:"$0",status:"Ready"},{part:"Hydraulic oil",number:"LUB-HYD-205",stock:"280 L",minimum:"180 L",cost:"$0",status:"Ready"},{part:"Pump seal kit",number:"KIT-PMP-793",stock:"1 kit",minimum:"2",cost:"$1,240",status:"Reorder"},{part:"Coolant concentrate",number:"CLT-50-205",stock:"90 L",minimum:"120 L",cost:"$780",status:"Reorder"}],
    maintenance:[{id:"MNT-088",type:"Predictive",date:"Aug 24, 2026",description:"Thermal scan found hydraulic temperature drift",condition:"Fair",cost:"$2,950"},{id:"MNT-074",type:"Preventive",date:"Jul 18, 2026",description:"Hydraulic oil and return-filter service",condition:"Good",cost:"$5,400"},{id:"MNT-061",type:"Corrective",date:"Jun 29, 2026",description:"Replaced cooling fan belt",condition:"Fair",cost:"$6,880"}], totalMaintenanceCost:"$21,680", operatingCost:"$11.85 / hour", predictedFailure:"Hydraulic pump wear" },
  { id:"NR-DR-03", name:"Blast-hole Drill 03", model:"Sandvik DR500", status:"Maintenance", condition:"Fair", risk:42, hours:"6,100", issue:"Feed pressure variance", predictedFailure:"Feed cylinder seal leak", totalMaintenanceCost:"$16,920", operatingCost:"$9.40 / hour",
    inventory:[{part:"Drill rod 89 mm",number:"WR-D89-600",stock:"36 available",minimum:"20",cost:"$0",status:"Ready"},{part:"Feed cylinder seal kit",number:"KIT-FEED-500",stock:"0 available",minimum:"2",cost:"$1,860",status:"No stock"},{part:"Compressor oil",number:"LUB-CMP-68",stock:"75 L",minimum:"60 L",cost:"$0",status:"Ready"},{part:"Dust collector filter",number:"FLT-DST-500",stock:"3 available",minimum:"5",cost:"$520",status:"Reorder"}],
    maintenance:[{id:"MNT-091",type:"Corrective",date:"Aug 27, 2026",description:"Feed pressure variance; seal wear confirmed",condition:"Fair",cost:"$4,620"},{id:"MNT-079",type:"Preventive",date:"Aug 02, 2026",description:"Compressor service and dust-filter inspection",condition:"Good",cost:"$3,850"},{id:"MNT-063",type:"Diagnostic",date:"Jun 21, 2026",description:"Investigated slow feed-cycle response",condition:"Fair",cost:"$5,100"}], totalMaintenanceCost:"$16,920", operatingCost:"$9.40 / hour", predictedFailure:"Feed cylinder seal leak" }
];

const recommendations = equipment.flatMap((asset)=>asset.inventory.filter((part)=>part.status!=="Ready").map((part)=>({...part, equipment:asset.id, urgency:part.status==="No stock"?"URGENT":asset.risk>=61?"HIGH":"ROUTINE", reason:asset.predictedFailure})));

function RiskBadge({score}:{score:number}){const tone=score>=61?"risk-red":score>=41?"risk-amber":"risk-green";const label=score>=81?"Critical":score>=61?"High":score>=41?"Medium":"Low";return <span className={`risk-badge ${tone}`}><span className="risk-dot"/>{label} · {score}</span>}
function StatCard({label,value,detail,icon:Icon,tone=""}:{label:string;value:string;detail:string;icon:typeof Boxes;tone?:string}){return <div className={`stat-card ${tone}`}><div className="stat-top"><span>{label}</span><Icon size={17}/></div><strong>{value}</strong><small>{detail}</small></div>}

export default function Home(){
 const [view,setView]=useState<View>("overview");
 const [history,setHistory]=useState<View[]>([]);
 const [selectedId,setSelectedId]=useState("NR-05");
 const [detailOpen,setDetailOpen]=useState(false);
 const [approved,setApproved]=useState<string[]>([]);
 const selected=equipment.find((item)=>item.id===selectedId) ?? equipment[0];
 const go=(next:View)=>{if(next===view)return;setHistory((items)=>[...items,view]);setView(next)};
 const back=()=>{const previous=history.at(-1);if(!previous)return;setHistory((items)=>items.slice(0,-1));setView(previous)};
 const openEquipment=(id:string)=>{setSelectedId(id);setDetailOpen(true)};
 const approve=(key:string)=>setApproved((items)=>items.includes(key)?items:[...items,key]);
 return <main className="app-shell">
  <aside className="sidebar"><div className="brand"><div className="brand-mark"><span/></div><div><b>RIDGELINE</b><small>Mining operations</small></div></div><div className="site-selector"><MapPin size={15}/><span>North Ridge Mine</span><ChevronRight size={15}/></div><p className="nav-label">Workspace</p><nav>{nav.map(([id,label,Icon])=><button key={id} className={view===id?"nav-item active":"nav-item"} onClick={()=>go(id as View)}><Icon size={17}/><span>{label}</span>{id==="overview"&&<span className="nav-count">4</span>}</button>)}</nav><p className="nav-label lower">Manage</p><nav><button className="nav-item" onClick={()=>go("maintenance")}><CalendarDays size={17}/><span>Maintenance calendar</span></button><button className="nav-item" onClick={()=>go("inventory")}><PackageCheck size={17}/><span>Purchase orders</span></button><button className="nav-item"><Settings2 size={17}/><span>Configuration</span></button></nav><div className="sidebar-footer"><div className="avatar">JM</div><div><b>Jordan McKay</b><small>Maintenance supervisor</small></div><ChevronRight size={15}/></div></aside>
  <section className="main-area"><header className="topbar"><div className="title-line">{history.length>0&&<button className="back-button" onClick={back} aria-label="Go back"><ArrowLeft size={16}/></button>}<div><span className="eyebrow">WEDNESDAY · 13 SEP 2026</span><h1>{view==="overview"?"Operations overview":view==="equipment"?"Equipment status":view==="inventory"?"Inventory status":"Maintenance history"}</h1></div></div><div className="top-actions"><div className="search"><Search size={16}/><input placeholder="Search equipment or parts"/></div><button className="icon-button" aria-label="Notifications"><Bell size={18}/><i/></button><div className="top-avatar">JM</div></div></header>
  {view==="overview"&&<Overview go={go} openEquipment={openEquipment} approved={approved} approve={approve}/>}
  {view==="equipment"&&<EquipmentView go={go} openEquipment={openEquipment}/>}
  {view==="inventory"&&<InventoryView assets={equipment} approved={approved} approve={approve} selectedId={selectedId} setSelectedId={setSelectedId}/>}
  {view==="maintenance"&&<MaintenanceView assets={equipment} openEquipment={openEquipment}/>}
  </section>
  {detailOpen&&<Detail asset={selected} go={go} close={()=>setDetailOpen(false)}/>}
 </main>
}

function Overview({go,openEquipment,approved,approve}:{go:(v:View)=>void;openEquipment:(id:string)=>void;approved:string[];approve:(x:string)=>void}){return <div className="content"><div className="hero-row"><div><p className="section-kicker">NORTH RIDGE · LIVE READINESS</p><h2>Good morning, Jordan.</h2><p className="muted">There are four decisions that need attention before the next shift starts.</p></div><button className="outline-button"><Filter size={15}/> Last 90 days <ChevronRight size={14}/></button></div><div className="stats-grid"><StatCard label="Equipment at risk" value="3" detail="1 critical · 2 high / medium" icon={ShieldAlert} tone="red"/><StatCard label="Parts below minimum" value="7" detail="$13,275 recommended spend" icon={Boxes} tone="amber"/><StatCard label="Overdue maintenance" value="2" detail="Oldest is 12 days overdue" icon={Clock3}/><StatCard label="Open work orders" value="6" detail="3 waiting on parts" icon={ClipboardCheck}/></div><div className="grid-main"><div className="panel risk-panel"><div className="panel-header"><div><h3>Equipment needing attention</h3><p>Each asset has its own health, cost, stock, and maintenance story.</p></div><button className="text-button" onClick={()=>go("equipment")}>View all <ArrowUpRight size={14}/></button></div><div className="equipment-list">{equipment.map(item=><button className="equipment-row" key={item.id} onClick={()=>openEquipment(item.id)}><div className="equipment-icon"><Truck size={19}/></div><div className="equipment-info"><b>{item.id} · {item.name}</b><span>{item.model} · {item.hours} operating hours</span></div><RiskBadge score={item.risk}/><span className="row-issue">{item.issue}</span><ChevronRight size={16} className="row-chevron"/></button>)}</div></div><div className="panel readiness-panel"><div className="panel-header"><div><h3>Shift readiness</h3><p>Parts coverage by equipment</p></div><CircleGauge size={19} className="panel-icon"/></div><div className="readiness-score"><strong>74%</strong><span>ready to respond</span></div><div className="progress"><span style={{width:"74%"}}/></div><div className="readiness-rows"><div><span className="status-dot green"/>NR-05 <b>1 / 4 ready</b></div><div><span className="status-dot amber"/>NR-12 <b>2 / 4 ready</b></div><div><span className="status-dot green"/>NR-DR-03 <b>2 / 4 ready</b></div></div><button className="wide-button" onClick={()=>go("inventory")}>Review parts coverage <ArrowUpRight size={15}/></button></div></div><div className="panel recommendations"><div className="panel-header"><div><h3>Recommended actions</h3><p>Prioritized from current risk and stock position</p></div><button className="text-button" onClick={()=>go("inventory")}>Open inventory <ArrowUpRight size={14}/></button></div><RecommendationTable items={recommendations.slice(0,4)} approved={approved} approve={approve}/></div></div>}

function EquipmentView({openEquipment}:{go:(v:View)=>void;openEquipment:(id:string)=>void}){return <div className="content"><div className="hero-row"><div><p className="section-kicker">FLEET HEALTH · 3 ASSETS</p><h2>Equipment status</h2><p className="muted">Select an asset to inspect its unique prediction, inventory, cost, and maintenance data.</p></div><button className="outline-button"><Filter size={15}/> All equipment <ChevronRight size={14}/></button></div><div className="panel equipment-full"><div className="panel-header"><div><h3>Fleet risk register</h3><p>Risk-ranked by current condition and maintenance signals.</p></div></div>{equipment.map(item=><button className="equipment-card" key={item.id} onClick={()=>openEquipment(item.id)}><div className="equipment-icon large"><Truck size={24}/></div><div className="equipment-info"><b>{item.id} · {item.name}</b><span>{item.model} · {item.status} · {item.hours} hours</span></div><div className="equipment-condition"><small>Maintenance cost</small><b>{item.totalMaintenanceCost}</b></div><RiskBadge score={item.risk}/><span className="row-issue">{item.predictedFailure}</span><ChevronRight size={17}/></button>)}</div></div>}

function InventoryView({assets,approved,approve,selectedId,setSelectedId}:{assets:EquipmentProfile[];approved:string[];approve:(x:string)=>void;selectedId:string;setSelectedId:(x:string)=>void}){const asset=assets.find((item)=>item.id===selectedId)??assets[0];return <div className="content"><div className="hero-row"><div><p className="section-kicker">NORTH RIDGE WAREHOUSE · 120 CONSUMPTION RECORDS</p><h2>Inventory status</h2><p className="muted">Stock position and reorder recommendations are separated by equipment.</p></div><button className="outline-button"><Filter size={15}/> All categories <ChevronRight size={14}/></button></div><div className="asset-tabs">{assets.map(item=><button key={item.id} className={item.id===selectedId?"asset-tab active":"asset-tab"} onClick={()=>setSelectedId(item.id)}><Truck size={15}/><span>{item.id}</span><RiskBadge score={item.risk}/></button>)}</div><div className="equipment-summary"><div><span>Selected equipment</span><b>{asset.id} · {asset.name}</b><small>{asset.model} · {asset.operatingCost} operating cost</small></div><div><span>Maintenance spend (90 days)</span><b>{asset.totalMaintenanceCost}</b><small>Based on {asset.maintenance.length} maintenance records</small></div><div><span>Likely failure</span><b>{asset.predictedFailure}</b><small>Risk <RiskBadge score={asset.risk}/></small></div></div><div className="panel recommendations inventory-table"><div className="panel-header"><div><h3>{asset.id} spare parts coverage</h3><p>Unique stock levels and costs for this asset.</p></div></div><RecommendationTable items={asset.inventory.filter((part)=>part.status!=="Ready").map((part)=>({...part,equipment:asset.id,urgency:part.status==="No stock"?"URGENT":"HIGH",reason:asset.predictedFailure}))} approved={approved} approve={approve}/></div><div className="panel ready-parts"><div className="panel-header"><div><h3>Available for {asset.id}</h3><p>Parts already above minimum level.</p></div></div><div className="ready-grid">{asset.inventory.filter((part)=>part.status==="Ready").map(part=><div className="ready-card" key={part.number}><span className="status-dot green"/><div><b>{part.part}</b><small>{part.stock} · Minimum {part.minimum}</small></div><strong>Ready</strong></div>)}</div></div></div>}

function RecommendationTable({items,approved,approve}:{items:Array<PartLine & {equipment:string;urgency:string;reason:string}>;approved:string[];approve:(x:string)=>void}){return <div className="recommendation-table"><div className="table-head"><span>Priority</span><span>Part</span><span>Stock position</span><span>Equipment impact</span><span>Cost</span><span/></div>{items.map(rec=>{const key=rec.equipment+rec.number;return <div className="table-row" key={key}><span><b className={`priority ${rec.urgency==="URGENT"?"red":rec.urgency==="HIGH"?"amber":"green"}`}>{rec.urgency}</b></span><span><b>{rec.part}</b><small>{rec.number}</small></span><span><b>{rec.stock}</b><small>Minimum {rec.minimum}</small></span><span><b>{rec.equipment}</b><small>{rec.reason}</small></span><span><b>{rec.cost}</b><small>recommended</small></span><span><button className={approved.includes(key)?"approve approved":"approve"} onClick={()=>approve(key)}>{approved.includes(key)?"Approved":"Approve"}</button></span></div>})}</div>}

function MaintenanceView({assets,openEquipment}:{assets:EquipmentProfile[];openEquipment:(id:string)=>void}){return <div className="content"><div className="hero-row"><div><p className="section-kicker">MAINTENANCE RECORDS · LAST 90 DAYS</p><h2>Maintenance history</h2><p className="muted">Every asset has a separate timeline, cost profile, and recurring issue pattern.</p></div><button className="outline-button"><CalendarDays size={15}/> Last 90 days <ChevronRight size={14}/></button></div><div className="maintenance-grid">{assets.map(asset=><div className="panel timeline-panel" key={asset.id}><div className="panel-header"><div><h3>{asset.id} · {asset.name}</h3><p>{asset.maintenance.length} records · 90-day spend {asset.totalMaintenanceCost}</p></div><RiskBadge score={asset.risk}/></div><div className="timeline compact">{asset.maintenance.map(line=><div className="timeline-item" key={line.id}><div className="timeline-marker"><Wrench size={14}/></div><div className="timeline-content"><div><b>{line.type} maintenance</b><span>{line.date}</span></div><p>{line.description}</p><small>{line.id} · <strong>{line.cost}</strong> · Condition after: <strong>{line.condition}</strong></small></div></div>)}</div><button className="text-button timeline-link" onClick={()=>openEquipment(asset.id)}>Open equipment detail <ArrowUpRight size={14}/></button></div>)}</div></div>}

function Detail({asset,go,close}:{asset:EquipmentProfile;go:(v:View)=>void;close:()=>void}){return <div className="detail-overlay" onClick={close}><aside className="detail-drawer" onClick={e=>e.stopPropagation()}><div className="drawer-header"><div><span className="eyebrow">EQUIPMENT DETAIL</span><h2>{asset.id} · {asset.name}</h2></div><button className="close-button" onClick={close}>×</button></div><div className="detail-metrics"><div><span>Risk</span><b>{asset.risk}/100</b><RiskBadge score={asset.risk}/></div><div><span>90-day maintenance</span><b>{asset.totalMaintenanceCost}</b><small>{asset.maintenance.length} records</small></div><div><span>Operating cost</span><b>{asset.operatingCost}</b><small>{asset.hours} total hours</small></div></div><div className="risk-hero"><div><span>Likely failure</span><strong>{asset.predictedFailure}</strong><p>Estimated intervention window: <b>{asset.risk>=61?"3–7 days":"14–30 days"}</b></p></div><div className="risk-ring"><span>{asset.risk}</span></div></div><div className="drawer-section"><h3>Inventory for {asset.id}</h3><div className="drawer-inventory">{asset.inventory.map(part=><div key={part.number}><span className={`status-dot ${part.status==="Ready"?"green":part.status==="No stock"?"red":"amber"}`}/><div><b>{part.part}</b><small>{part.stock} · Minimum {part.minimum}</small></div><strong>{part.status}</strong></div>)}</div></div><div className="drawer-section"><h3>Recent maintenance</h3><div className="drawer-history">{asset.maintenance.slice(0,3).map(line=><div key={line.id}><b>{line.date}</b><span>{line.description}</span><small>{line.cost}</small></div>)}</div></div><button className="primary-button" onClick={()=>{close();go("inventory")}}>Review {asset.id} parts <ArrowUpRight size={16}/></button></aside></div>}

