"use client";

import { useState } from "react";
import { AlertTriangle, ArrowUpRight, Bell, Boxes, CalendarDays, ChevronRight, CircleGauge, ClipboardCheck, Clock3, Filter, Gauge, LayoutDashboard, MapPin, PackageCheck, Search, Settings2, ShieldAlert, Truck, Wrench } from "lucide-react";

type View = "overview" | "equipment" | "inventory" | "maintenance";
const nav = [["overview","Operations overview",LayoutDashboard],["equipment","Equipment status",Truck],["inventory","Inventory status",Boxes],["maintenance","Maintenance history",Wrench]] as const;
const equipment = [
  {id:"NR-05",name:"Haul Truck 05",model:"CAT 797F",status:"Operational",condition:"Poor",risk:82,hours:"12,400",issue:"Oil pressure warning"},
  {id:"NR-12",name:"Haul Truck 12",model:"CAT 793F",status:"Operational",condition:"Fair",risk:58,hours:"8,200",issue:"Hydraulic temperature"},
  {id:"NR-DR-03",name:"Blast-hole Drill 03",model:"Sandvik DR500",status:"Maintenance",condition:"Fair",risk:42,hours:"6,100",issue:"Feed pressure variance"}
];
const recommendations = [
  {part:"Heavy-duty engine oil 15W-40",number:"LUB-15W40-205",stock:"45 L",minimum:"100 L",daily:"8.2 L/day",days:"5 days",qty:"200 L",cost:"$1,900",urgency:"URGENT",color:"red",reason:"Three haul trucks are trending fair or poor; lead time is 2 days."},
  {part:"Engine oil filter",number:"FLT-ENG-797",stock:"1 available",minimum:"5",daily:"0.18/day",days:"6 days",qty:"15",cost:"$2,775",urgency:"HIGH",color:"amber",reason:"NR-05 has recurring oil-pressure warnings and a filter is reserved."},
  {part:"Engine bearing set",number:"BRG-ENG-797",stock:"0 available",minimum:"1",daily:"0.02/day",days:"0 days",qty:"1 set",cost:"$3,200",urgency:"URGENT",color:"red",reason:"Critical prediction: bearing failure is the most likely failure mode."},
  {part:"Engine gasket set",number:"KIT-GSK-797",stock:"1 set",minimum:"2",daily:"0.03/day",days:"31 days",qty:"2 sets",cost:"$2,900",urgency:"ROUTINE",color:"green",reason:"Pre-stage ahead of the planned engine inspection."}
];
const maintenance = [["MNT-2026-093","Diagnostic","Aug 29, 2026","Recurring oil-pressure warning; bearing noise suspected"],["MNT-2026-081","Corrective","Aug 14, 2026","Inspected recurring lubrication issue"],["MNT-2026-067","Preventive","Jul 26, 2026","Scheduled engine service; abnormal vibration"],["MNT-2026-052","Corrective","Jul 02, 2026","Repaired engine oil leak; warning returned"],["MNT-2026-041","Corrective","Jun 11, 2026","Investigated low oil-pressure alarm"]];
function RiskBadge({score}:{score:number}){const tone=score>=61?"risk-red":score>=41?"risk-amber":"risk-green";const label=score>=81?"Critical":score>=61?"High":score>=41?"Medium":"Low";return <span className={`risk-badge ${tone}`}><span className="risk-dot"/>{label} · {score}</span>}
function StatCard({label,value,detail,icon:Icon,tone=""}:{label:string;value:string;detail:string;icon:typeof Boxes;tone?:string}){return <div className={`stat-card ${tone}`}><div className="stat-top"><span>{label}</span><Icon size={17}/></div><strong>{value}</strong><small>{detail}</small></div>}
export default function Home(){
 const [view,setView]=useState<View>("overview"); const [selected,setSelected]=useState(equipment[0]); const [showDetail,setShowDetail]=useState(false); const [approved,setApproved]=useState<string[]>([]);
 const approve=(part:string)=>setApproved(x=>x.includes(part)?x:[...x,part]);
 const open=(item:typeof equipment[number])=>{setSelected(item);setShowDetail(true)};
 const table=(items=recommendations)=> <div className="recommendation-table"><div className="table-head"><span>Priority</span><span>Part</span><span>Stock position</span><span>Recommendation</span><span>Cost</span><span/></div>{items.map(rec=><div className="table-row" key={rec.part}><span><b className={`priority ${rec.color}`}>{rec.urgency}</b></span><span><b>{rec.part}</b><small>{rec.number}</small></span><span><b>{rec.stock}</b><small>Minimum {rec.minimum} · {rec.daily}</small></span><span><b>{rec.qty}</b><small>{rec.reason}</small></span><span><b>{rec.cost}</b><small>{rec.days} to stockout</small></span><span><button className={approved.includes(rec.part)?"approve approved":"approve"} onClick={()=>approve(rec.part)}>{approved.includes(rec.part)?"Approved":"Approve"}</button></span></div>)}</div>;
 return <main className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark"><span/></div><div><b>RIDGELINE</b><small>Mining operations</small></div></div><div className="site-selector"><MapPin size={15}/><span>North Ridge Mine</span><ChevronRight size={15}/></div><p className="nav-label">Workspace</p><nav>{nav.map(([id,label,Icon])=><button key={id} className={view===id?"nav-item active":"nav-item"} onClick={()=>setView(id as View)}><Icon size={17}/><span>{label}</span>{id==="overview"&&<span className="nav-count">4</span>}</button>)}</nav><p className="nav-label lower">Manage</p><nav><button className="nav-item"><CalendarDays size={17}/><span>Maintenance calendar</span></button><button className="nav-item"><PackageCheck size={17}/><span>Purchase orders</span></button><button className="nav-item"><Settings2 size={17}/><span>Configuration</span></button></nav><div className="sidebar-footer"><div className="avatar">JM</div><div><b>Jordan McKay</b><small>Maintenance supervisor</small></div><ChevronRight size={15}/></div></aside><section className="main-area"><header className="topbar"><div><span className="eyebrow">WEDNESDAY · 13 SEP 2026</span><h1>{view==="overview"?"Operations overview":view==="equipment"?"Equipment status":view==="inventory"?"Inventory status":"Maintenance history"}</h1></div><div className="top-actions"><div className="search"><Search size={16}/><input placeholder="Search equipment or parts"/></div><button className="icon-button" aria-label="Notifications"><Bell size={18}/><i/></button><div className="top-avatar">JM</div></div></header>
 {view==="overview"&&<div className="content"><div className="hero-row"><div><p className="section-kicker">NORTH RIDGE · LIVE READINESS</p><h2>Good morning, Jordan.</h2><p className="muted">There are four decisions that need attention before the next shift starts.</p></div><button className="outline-button"><Filter size={15}/> Last 90 days <ChevronRight size={14}/></button></div><div className="stats-grid"><StatCard label="Equipment at risk" value="3" detail="1 critical · 2 high / medium" icon={ShieldAlert} tone="red"/><StatCard label="Parts below minimum" value="4" detail="$10,775 recommended spend" icon={Boxes} tone="amber"/><StatCard label="Overdue maintenance" value="2" detail="Oldest is 12 days overdue" icon={Clock3}/><StatCard label="Open work orders" value="6" detail="2 waiting on parts" icon={ClipboardCheck}/></div><div className="grid-main"><div className="panel risk-panel"><div className="panel-header"><div><h3>Equipment needing attention</h3><p>Risk score combines condition, hours, maintenance frequency, and recurring issues.</p></div><button className="text-button" onClick={()=>setView("equipment")}>View all <ArrowUpRight size={14}/></button></div><div className="equipment-list">{equipment.map(item=><button className="equipment-row" key={item.id} onClick={()=>open(item)}><div className="equipment-icon"><Truck size={19}/></div><div className="equipment-info"><b>{item.id} · {item.name}</b><span>{item.model} · {item.hours} operating hours</span></div><RiskBadge score={item.risk}/><span className="row-issue">{item.issue}</span><ChevronRight size={16} className="row-chevron"/></button>)}</div></div><div className="panel readiness-panel"><div className="panel-header"><div><h3>Shift readiness</h3><p>Parts coverage for predicted work</p></div><CircleGauge size={19} className="panel-icon"/></div><div className="readiness-score"><strong>74%</strong><span>ready to respond</span></div><div className="progress"><span style={{width:"74%"}}/></div><div className="readiness-rows"><div><span className="status-dot green"/>Available now <b>6 kits</b></div><div><span className="status-dot amber"/>Order required <b>3 kits</b></div><div><span className="status-dot red"/>No stock <b>1 kit</b></div></div><button className="wide-button" onClick={()=>setView("inventory")}>Review parts coverage <ArrowUpRight size={15}/></button></div></div><div className="panel recommendations"><div className="panel-header"><div><h3>Recommended actions</h3><p>Prioritized from current risk and stock position</p></div><button className="text-button" onClick={()=>setView("inventory")}>Open inventory <ArrowUpRight size={14}/></button></div>{table(recommendations.slice(0,3))}</div></div>}
 {view==="equipment"&&<div className="content"><div className="hero-row"><div><p className="section-kicker">FLEET HEALTH</p><h2>Equipment status</h2><p className="muted">Risk-ranked view of active assets at North Ridge.</p></div><button className="outline-button"><Filter size={15}/> All equipment <ChevronRight size={14}/></button></div><div className="panel equipment-full"><div className="panel-header"><div><h3>Fleet risk register</h3><p>Select an asset to inspect its prediction evidence.</p></div></div>{equipment.map(item=><button className="equipment-card" key={item.id} onClick={()=>open(item)}><div className="equipment-icon large"><Truck size={24}/></div><div className="equipment-info"><b>{item.id} · {item.name}</b><span>{item.model} · {item.status} · {item.hours} hours</span></div><div className="equipment-condition"><small>Condition</small><b>{item.condition}</b></div><RiskBadge score={item.risk}/><span className="row-issue">{item.issue}</span><ChevronRight size={17}/></button>)}</div></div>}
 {view==="inventory"&&<div className="content"><div className="hero-row"><div><p className="section-kicker">NORTH RIDGE WAREHOUSE · 120 CONSUMPTION RECORDS</p><h2>Inventory status</h2><p className="muted">Reorder recommendations are ranked by time to stockout and equipment impact.</p></div><button className="outline-button"><Filter size={15}/> All categories <ChevronRight size={14}/></button></div><div className="stats-grid"><StatCard label="Parts tracked" value="4" detail="Across 3 compatible assets" icon={Boxes}/><StatCard label="At reorder point" value="4" detail="100% of critical engine parts" icon={AlertTriangle} tone="amber"/><StatCard label="Estimated spend" value="$10.8k" detail="If all recommendations approved" icon={Gauge}/><StatCard label="Consumption history" value="90 days" detail="Average confidence: 0.78" icon={CircleGauge}/></div><div className="panel recommendations inventory-table"><div className="panel-header"><div><h3>Reorder recommendations</h3><p>Generated from stock, consumption, lead time, and equipment condition.</p></div></div>{table()}</div></div>}
 {view==="maintenance"&&<div className="content"><div className="hero-row"><div><p className="section-kicker">MAINTENANCE RECORDS · NR-05</p><h2>Maintenance history</h2><p className="muted">Recurring issues are surfaced beside the work they appeared in.</p></div><button className="outline-button"><CalendarDays size={15}/> Next 30 days <ChevronRight size={14}/></button></div><div className="panel timeline-panel"><div className="panel-header"><div><h3>Haul Truck 05 · service timeline</h3><p>Five records in the last 90 days · condition remains poor</p></div><RiskBadge score={82}/></div><div className="timeline">{maintenance.map(([id,type,date,description])=><div className="timeline-item" key={id}><div className="timeline-marker"><Wrench size={14}/></div><div className="timeline-content"><div><b>{type} maintenance</b><span>{date}</span></div><p>{description}</p><small>{id} · Condition after: <strong>Poor</strong></small></div></div>)}</div><div className="pattern-callout"><AlertTriangle size={18}/><div><b>Recurring pattern detected</b><p>Oil-pressure warnings have appeared three times in 90 days. Investigate the lubrication system during the recommended engine inspection.</p></div></div></div></div>}
 </section>{showDetail&&<div className="detail-overlay" onClick={()=>setShowDetail(false)}><aside className="detail-drawer" onClick={e=>e.stopPropagation()}><div className="drawer-header"><div><span className="eyebrow">PREDICTION DETAIL</span><h2>{selected.id} · {selected.name}</h2></div><button className="close-button" onClick={()=>setShowDetail(false)}>×</button></div><div className="risk-hero"><div><span>Failure risk</span><strong>{selected.risk}<small>/100</small></strong><RiskBadge score={selected.risk}/></div><div className="risk-ring"><span>{selected.risk}</span></div></div><div className="drawer-section"><h3>Likely failure</h3><div className="failure-card"><ShieldAlert size={18}/><div><b>Engine bearing failure</b><p>Estimated intervention window: <strong>3–7 days</strong></p></div></div></div><div className="drawer-section"><h3>Why the system is concerned</h3><ul className="factor-list"><li><b>12,400 hours</b><span>2,400 hours above overhaul threshold</span></li><li><b>Poor condition</b><span>Condition has not improved after recent service</span></li><li><b>5 services in 90 days</b><span>Maintenance frequency is increasing</span></li><li><b>3 oil-pressure warnings</b><span>Recurring issue points to lubrication system</span></li></ul></div><div className="drawer-section"><h3>Recommended response</h3><div className="action-list"><div><span>1</span><p>Schedule engine inspection within 3 days</p></div><div><span>2</span><p>Pre-stage oil, filters, gaskets, and bearing set</p></div><div><span>3</span><p>Prepare backup haul capacity for the next shift</p></div></div></div><button className="primary-button" onClick={()=>{setShowDetail(false);setView("inventory")}}>Review required parts <ArrowUpRight size={16}/></button></aside></div>}</main>
}
